---

app_options:
    php:                   true
    php_version:           '7.3'

app_patterns:
    timezone_default: UTC

    php_extensions:
        # Symfony
        - intl
        - curl
        - mbstring
        - xml
        # App

    php_configs:
        - file: app_opcache.ini
          template: configs/app_opcache.{{ env }}.j2
        - file: app.ini
          template: configs/app.{{ env }}.j2
          config:
              - date.timezone: UTC
