name: CI

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    # Event "pull_request_target" is for Dependabot, since PR created by Dependabot are now treated as if they were opened from a fork.
    # See: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
    pull_request_target:
        types: [opened, synchronize, reopened, ready_for_review]

env:
    TZ: UTC

    PHPUNIT_FLAGS: -v
    COMPOSER_MEMORY_LIMIT: -1

jobs:
    static_analysis:
        runs-on: ubuntu-latest
        # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
        # Otherwise, clone it normally.
        if: |
            (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
            (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
        steps:
            - name: Checkout
              if: ${{ github.event_name != 'pull_request_target' }}
              uses: actions/checkout@v2

            - name: Checkout PR
              if: ${{ github.event_name == 'pull_request_target' }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            -   name: Install PHP
                uses: shivammathur/setup-php@2.12.0
                with:
                    php-version: 7.3
                    ini-values: date.timezone=${{ env.TZ }}, memory_limit=-1, session.gc_probability=0, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=20000, opcache.validate_timestamps=0, realpath_cache_size=4096K, realpath_cache_ttl=600

            -   run: composer install --prefer-dist --no-interaction --no-progress

            -   run: composer phpunit -- install

            -   run: composer validate --strict

            -   run: composer phpspec -- run

            -   run: composer phpstan

            -   run: composer php-cs-fixer@ci

    test:
        runs-on: ubuntu-latest
        # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
        # Otherwise, clone it normally.
        if: |
            (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
            (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
        strategy:
            fail-fast: false
            matrix:
                config:
                    # Minimum supported dependencies with the latest and oldest PHP version
                    -   PHP_VERSION: 7.3
                        COMPOSER_FLAGS: --prefer-stable --prefer-lowest
                    -   PHP_VERSION: 7.4
                        COMPOSER_FLAGS: --prefer-stable --prefer-lowest

                    # Test the latest stable release
                    -   PHP_VERSION: 7.3
                    -   PHP_VERSION: 7.4
                        COVERAGE: true
                        PHPUNIT_FLAGS: -v --coverage-text

                    # Test specific Symfony versions
                    -   PHP_VERSION: 7.3
                        SYMFONY_VERSION: 4.4.* # LTS
                    -   PHP_VERSION: 7.4
                        SYMFONY_VERSION: 4.4.* # LTS

                    -   PHP_VERSION: 7.3
                        SYMFONY_VERSION: 5.0.*
                    -   PHP_VERSION: 7.4
                        SYMFONY_VERSION: 5.0.*

                    -   PHP_VERSION: 7.3
                        SYMFONY_VERSION: 5.1.*
                    -   PHP_VERSION: 7.4
                        SYMFONY_VERSION: 5.1.*

        steps:
            - name: Checkout
              if: ${{ github.event_name != 'pull_request_target' }}
              uses: actions/checkout@v2

            - name: Checkout PR
              if: ${{ github.event_name == 'pull_request_target' }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            -   name: Install PHP
                uses: shivammathur/setup-php@2.12.0
                with:
                    php-version: ${{ matrix.config.PHP_VERSION }}
                    coverage: ${{ matrix.config.COVERAGE }}
                    ini-values: date.timezone=${{ env.TZ }}, memory_limit=-1, session.gc_probability=0, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=20000, opcache.validate_timestamps=0, realpath_cache_size=4096K, realpath_cache_ttl=600

            -   name: Configure Composer minimum stability
                if: matrix.config.STABILITY
                run: composer config minimum-stability ${{ matrix.config.STABILITY }}

            -   name: Install globally Symfony Flex
                run: composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-main

            -   name: Limit to specific Symfony version
                if: matrix.config.SYMFONY_VERSION
                run: echo "SYMFONY_REQUIRE=${{matrix.config.SYMFONY_VERSION}}" >> $GITHUB_ENV

            -   name: Install composer dependencies
                run: composer update ${{ matrix.config.COMPOSER_FLAGS }} --prefer-dist --no-interaction

            -   name: Run PHPUnit
                run: composer phpunit -- ${{ matrix.config.PHPUNIT_FLAGS }}

    auto_merge:
        runs-on: ubuntu-latest
        needs: [static_analysis, test]
        if: ${{ github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
        steps:
            - name: Checkout
              if: ${{ github.event_name != 'pull_request_target' }}
              uses: actions/checkout@v2

            - name: Checkout PR
              if: ${{ github.event_name == 'pull_request_target' }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: ahmadnassri/action-dependabot-auto-merge@v2
              with:
                  github-token: ${{ secrets.ACTION_DEPENDABOT_AUTO_MERGE_TOKEN }}
